version: '2'

services:

  freeradius:
    build: . #use "/Radius" if you copy this to your main docker-compose-file!
    #image: philleconnect/radiusserver:v0.9beta
    restart: always
    ports:
     - "1812:1812/udp"
     - "1813:1813"
     - "18120:18120"
    env_file:
     - ./settings.env
#    networks:
#      philleconnect:

networks:
    default:
        external:
            name: servercontainers_philleconnect
